spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/postgres
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            redirect-uri: ${GOOGLE_REDIRECTURL}
            scope:
              - email
              - profile